apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-argocd-oauth-client
spec:
  data:
    - remoteRef:
        key: secret/github-oauth-argo-client-id
      secretKey: client-id
    - remoteRef:
        key: secret/github-oauth-argo-client-secret
      secretKey: client-secret
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-key-vault-store
  target:
    deletionPolicy: Delete