apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: aso-controller-settings
spec:
  data:
    - remoteRef:
        key: secret/subscription-id
      secretKey: AZURE_SUBSCRIPTION_ID
    - remoteRef:
        key: secret/tenant-id
      secretKey: AZURE_TENANT_ID
    - remoteRef:
        key: secret/aso-managed-identity-client-id
      secretKey: AZURE_CLIENT_ID
    - remoteRef:
        key: secret/aso-use-workload-identity-auth
      secretKey: USE_WORKLOAD_IDENTITY_AUTH
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-key-vault-store
  target:
    deletionPolicy: Delete