apiVersion: resources.azure.com/v1api20200601
kind: ResourceGroup
metadata:
  name: daniel-grob-rg
spec:
  location: westeurope
---
apiVersion: keyvault.azure.com/v1api20210401preview
kind: Vault
metadata:
  name: daniel-grob-vault
spec:
  location: westeurope
  owner:
    name: daniel-grob-rg
  properties:
    tenantId: "1144570c-494c-493e-8d7d-9da713eca2a4"
    sku:
      family: A
      name: standard
    accessPolicies: []
