apiVersion: resources.azure.com/v1api20200601
kind: ResourceGroup
metadata:
  name: daniel-grob-rg
spec:
  location: westeurope
---
apiVersion: keyvault.azure.com/v1api20210401preview
kind: Vault
metadata:
  name: daniel-grob-vault
  namespace: default
spec:
  location: westeurope
  owner:
    name: daniel-grob-rg
  properties:
    sku:
      family: A
      name: standard
