apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "camp-chart.fullname" . }}
  labels:
    {{- include "camp-chart.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "camp-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "camp-chart.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "camp-chart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          env: {{- if gt (len .Values.env) 0 }}{{- toYaml .Values.env | nindent 12 }}{{- end }}
            {{- range $ref := .Values.externalSecret.refs }}
              {{- /* Cannot use default as it second value is false, default value is taken. https://github.com/Masterminds/sprig/issues/111#issuecomment-701368182 */}}
              {{- if (ternary $ref.addAsEnv $.Values.externalSecret.addAsEnv (not (kindIs "invalid" $ref.addAsEnv ))) }}
            - name: {{ default $ref.vaultKey $ref.secretKey }}
              valueFrom:
                secretKeyRef:
                  name: {{ include "generic-chart.externalSecretName" $ }}
                  key: {{ default $ref.vaultKey $ref.secretKey }}
              {{- end }}
            {{- end }}
            {{- range $key, $val := .Values.network }}
              {{- if $val.ingress }}
                {{- if $val.ingress.addAsEnv }}
            - name: {{ default ( printf "INGRESS_HOST_%s" $key | upper ) $val.ingress.envNameOverride }}
              value: {{ $val.ingress.host }}
                {{- end }}
              {{- end }}
            {{- end }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
