{{- if .Values.ingress.enabled -}}
{{- $fullName := include "camp-chart.fullname" . -}}
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "camp-chart.labels" . | nindent 4 }}
spec:
  endpoints:
    - dnsName: {{ if .Values.ingress.subdomain }}{{ .Values.ingress.subdomain }}{{ else }}{{ template "camp-chart.namespace" $ }}{{ end }}.{{ .Values.ingress.domain}}
      recordTTL: 180
      recordType: CNAME
      targets:
        - {{ .Values.ingress.domain}}
{{- end }}
