{{- if .Values.ingress.enabled -}}
{{- $fullName := include "camp-chart.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "camp-chart.labels" . | nindent 4 }}
  annotations:
    cert-manager.io/cluster-issuer: cloudflare-lets-encrypt
    kubernetes.io/tls-acme: "true"
spec:
  ingressClassName: "nginx"
  tls:
    - hosts:
        - {{ .Values.ingress.subdomain }}.{{ .Values.ingress.domain}}
      secretName: nginx-cert
  rules:
    - host: {{ .Values.ingress.subdomain }}.{{ .Values.ingress.domain}}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
{{- end }}
