apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-api-key
spec:
  data:
    - remoteRef:
        key: secret/cloudflare-api-key
      secretKey: api-key
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-key-vault-store
  target:
    deletionPolicy: Delete