apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: azure-key-vault-store
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      vaultUrl: https://kv-flying-teal.vault.azure.net/
      serviceAccountRef:
        name: externalsecretsoperator-default
        namespace: external-secrets
