apiVersion: resources.azure.com/v1api20200601
kind: ResourceGroup
metadata:
  name: azure-vote-rg
spec:
  location: westeurope
---
apiVersion: cache.azure.com/v1api20201201
kind: Redis
metadata:
  name: azure-vote-redis
spec:
  location: westeurope
  owner:
    name: azure-vote-rg
  sku:
    name: Basic
    family: C
    capacity: 1
  enableNonSslPort: true
  minimumTlsVersion: "1.2"
  redisConfiguration:
    maxmemory-delta: "10"
    maxmemory-policy: allkeys-lru
  redisVersion: "6"
  operatorSpec:
    secrets:
      hostName:
        name: redis-hostname
        key: hostName
      primaryKey:
        name: redis-access-key
        key: primaryKey
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-vote-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azure-vote-front
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: azure-vote-front
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: azure-vote-front
        image: mcr.microsoft.com/azuredocs/azure-vote-front:v1
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
        env:
        - name: REDIS
          valueFrom:
            secretKeyRef:
              name: redis-hostname
              key: hostName
              optional: false
        - name: REDIS_PWD
          valueFrom:
            secretKeyRef:
              name: redis-access-key
              key: primaryKey
              optional: false
---
apiVersion: v1
kind: Service
metadata:
  name: azure-vote-front
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: azure-vote-front