apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.8.0/manifests/install.yaml
  - base/default-app-project.yaml
  - base/bootstrap-application-set.yaml

patchesStrategicMerge:
  - overlays/argocd-server-service.yaml
  - overlays/argocd-cm.yaml

