apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-api-token
  namespace: external-dns
spec:
  data:
    - remoteRef:
        key: secret/cloudflare-api-token
      secretKey: api-token
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-key-vault-store
  target:
    deletionPolicy: Delete