apiVersion: managedidentity.azure.com/v1api20181130
kind: UserAssignedIdentity
metadata:
  name: mid-event-grid-publisher
spec:
  location: westeurope
  owner:
    name: rg-event-grid
  operatorSpec:
    configMaps:
      principalId:
        name: identity-settings
        key: principalId
      clientId:
        name: identity-settings
        key: clientId