apiVersion: authorization.azure.com/v1api20200801preview
kind: RoleAssignment
metadata:
  name: ra-topic
spec:
  # This resource can be owner by any resource. In this example we've chosen a resource group for simplicity
  owner:
    name: rg-event-grid
    group: resources.azure.com
    kind: ResourceGroup
  # This is the Principal ID of the AAD identity to which the role will be assigned
  principalIdFromConfig:
    name: identity-settings
    key: principalId
  roleDefinitionReference:
    # This ARM ID represents "Contributor" - you can read about other built in roles here: https://docs.microsoft.com/en-us/azure/role-based-access-control/built-in-roles
    armId: /subscriptions/9433ade8-772f-4fea-97a7-eadf8c869c67/providers/Microsoft.Authorization/roleDefinitions/8e3af657-a8ff-443c-a75c-2fe8c4bcb635