voting-app-next:
  image:
    repository: mcr.microsoft.com/azuredocs/azure-vote-front
    tag: v1
  rg:
    enabled: true
  env:
    - name: REDIS
      valueFrom:
        secretKeyRef:
          name: redis-hostname
          key: hostName
          optional: false
    - name: REDIS_PWD
      valueFrom:
        secretKeyRef:
          name: redis-access-key
          key: primaryKey
          optional: false